apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-repo/demo-dev.git'
    targetRevision: HEAD
    path: applications/app1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
