apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-github-username/HelmCharts
    targetRevision: HEAD
    path: ChartTest1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
